const players=[{name:'Ghost',tag:'GH',rating:2486,win:68,kd:2.14,matches:342,color:'#c5f36b'},{name:'Valkyrie',tag:'VK',rating:2410,win:65,kd:1.98,matches:298,color:'#b9acff'},{name:'Reaper',tag:'RP',rating:2374,win:63,kd:1.87,matches:416,color:'#ffb17a'},{name:'Nomad',tag:'NM',rating:2318,win:61,kd:1.76,matches:267,color:'#7ad4df'},{name:'Wolf',tag:'WF',rating:2295,win:60,kd:1.72,matches:389,color:'#eb99bc'}];
const matches=[{id:'DEMO-1048',map:'Industrial zone',mode:'Командный бой',result:'Победа',score:'32 / 14 / 8',time:'28:42'},{id:'DEMO-1047',map:'Outpost',mode:'Контроль',result:'Поражение',score:'18 / 19 / 6',time:'24:16'},{id:'DEMO-1046',map:'Industrial zone',mode:'Командный бой',result:'Победа',score:'27 / 12 / 11',time:'31:05'},{id:'DEMO-1045',map:'Borderlands',mode:'Контроль',result:'Победа',score:'24 / 15 / 9',time:'26:38'}];
const content=document.querySelector('#content');
const avatar=p=>`<span class="avatar" style="--accent:${p.color}">${p.tag}</span>`;
function ranking(list=players){return `<div class="table-wrap"><table><thead><tr><th>#</th><th>Игрок</th><th>Рейтинг ↓</th><th>Победы</th><th>K/D</th><th>Матчи</th></tr></thead><tbody>${list.map(p=>`<tr><td class="muted">${players.indexOf(p)+1 < 10?'0':''}${players.indexOf(p)+1}</td><td><button class="player" data-player="${p.name}">${avatar(p)}<span>${p.name}<small>Демо-профиль</small></span></button></td><td class="rating">${p.rating.toLocaleString('ru')}</td><td>${p.win}% <span class="bar"><i style="width:${p.win}%"></i></span></td><td>${p.kd.toFixed(2)}</td><td class="muted">${p.matches}</td></tr>`).join('')}</tbody></table></div>`;}
function matchTable(){return `<div class="table-wrap"><table><thead><tr><th>Матч</th><th>Карта / режим</th><th>Результат Ghost</th><th>K / D / A</th><th>Время</th></tr></thead><tbody>${matches.map(m=>`<tr><td class="muted">${m.id}</td><td>${m.map}<small>${m.mode}</small></td><td class="${m.result==='Победа'?'win':'loss'}">${m.result}</td><td>${m.score}</td><td class="muted">${m.time}</td></tr>`).join('')}</tbody></table></div>`;}
function heading(title,sub){return `<div class="section-head"><div><div class="eyebrow">FIELD REPORT / DEMO</div><h2>${title}</h2></div><span class="muted">${sub}</span></div>`;}
function render(tab='overview'){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='matches'){content.innerHTML=heading('История матчей','Демо-профиль Ghost')+matchTable();return;}if(tab==='players'){content.innerHTML=heading('Рейтинг игроков','5 демонстрационных профилей')+ranking();return;}content.innerHTML=`<div class="stats"><article><span>Игроков в демо</span><strong>05<sup>↗</sup></strong><small>Профили для знакомства</small></article><article><span>Матчей Ghost</span><strong>342</strong><small>Демонстрационная статистика</small></article><article><span>Победы Ghost</span><strong>68<sup>%</sup></strong><small>Демонстрационная статистика</small></article><article><span>Лучший рейтинг</span><strong>2 486</strong><small>Ghost / демо-лидер</small></article></div>${heading('На вершине рейтинга','Рейтинг · демонстрационная выборка')}${ranking()}<div class="bottom-grid"><article class="feature"><div class="eyebrow">PLAYER SPOTLIGHT</div><h2>Встречай Ghost.</h2><p>68% побед. 2.14 K/D.<br>Посмотри, как выглядит профиль игрока.</p><button data-player="Ghost">Открыть профиль ↗</button><span class="ghost-art" aria-hidden="true">GH</span></article><article class="about"><div class="eyebrow">ТВОЯ ИГРА, В ДЕТАЛЯХ</div><h2>За цифрами —<br>твой прогресс.</h2><p>Следи за результатами, сравнивай игроков и изучай историю матчей. Сейчас доступно демо; реальные данные появятся после подключения API игры.</p><button data-tab="matches">Посмотреть матчи →</button></article></div>`;}
function profile(name){const p=players.find(p=>p.name===name);content.innerHTML=`<button class="back" data-tab="players">← Все игроки</button><div class="profile-head">${avatar(p)}<div><div class="eyebrow">ДЕМОНСТРАЦИОННЫЙ ПРОФИЛЬ</div><h2>${p.name}</h2></div></div><div class="stats">${[['Рейтинг',p.rating],['Победы',p.win+'%'],['K/D',p.kd],['Матчи',p.matches]].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong><small>Демо-данные</small></article>`).join('')}</div>${p.name==='Ghost'?heading('Последние матчи','История Ghost')+matchTable():`<div class="empty">История матчей этого демо-профиля пока не добавлена.</div>`}`;}
document.addEventListener('click',e=>{const p=e.target.closest('[data-player]');const t=e.target.closest('[data-tab]');if(p)profile(p.dataset.player);else if(t)render(t.dataset.tab);});
document.querySelector('#search').addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#query').value.trim().toLowerCase();if(!q){render('players');return;}const found=players.filter(p=>p.name.toLowerCase().includes(q));content.innerHTML=heading('Результаты поиска',`${found.length} найдено`)+(found.length?ranking(found):'<div class="empty">Игрок не найден. В демо доступны Ghost, Valkyrie, Reaper, Nomad и Wolf.</div>');content.scrollIntoView({behavior:'smooth',block:'start'});});render();
